USE [master]
GO

/****** Object:  Database [QuanLyNhaSach]    Script Date: 9/7/2024 3:10:15 PM ******/
CREATE DATABASE [QuanLyNhaSach]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLyNhaSach', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\QuanLyNhaSach.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanLyNhaSach_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\QuanLyNhaSach_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLyNhaSach].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QuanLyNhaSach] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET ARITHABORT OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QuanLyNhaSach] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QuanLyNhaSach] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QuanLyNhaSach] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [QuanLyNhaSach] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QuanLyNhaSach] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET RECOVERY FULL 
GO

ALTER DATABASE [QuanLyNhaSach] SET  MULTI_USER 
GO

ALTER DATABASE [QuanLyNhaSach] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QuanLyNhaSach] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QuanLyNhaSach] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QuanLyNhaSach] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [QuanLyNhaSach] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QuanLyNhaSach] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QuanLyNhaSach] SET QUERY_STORE = ON
GO

ALTER DATABASE [QuanLyNhaSach] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [QuanLyNhaSach] SET  READ_WRITE 
GO

